(()=>{
const app=document.getElementById("app"), CFG=window.MAIKL_CONFIG, SERVICES=window.MAIKL_SERVICES, T=window.MAiKLTime, API=window.MAiKLAPI;
let state={route:"home",service:null,dayOffset:0,selectedDay:null,selected:null,bookings:[],zone:T.localZone()};
function tg(){return window.Telegram?.WebApp||null}try{tg()?.ready();tg()?.expand();tg()?.setHeaderColor?.("#ffffff");tg()?.setBackgroundColor?.("#ffffff")}catch(_){ }
function user(){const u=tg()?.initDataUnsafe?.user;return {key:u?`tg:${u.id}`:`web:${getWebId()}`,name:u?.first_name||"Гость",telegramId:u?.id||null}}
function getWebId(){try{let x=localStorage.getItem("maikl_web_id");if(!x){x=(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():`demo-${Date.now()}-${Math.random().toString(16).slice(2)}`;localStorage.setItem("maikl_web_id",x)}return x}catch(_){return `demo-${Date.now()}`}}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function rub(n){return new Intl.NumberFormat("ru-RU").format(n)+" ₽"}
function logo(){return `<img class="logo" src="assets/logo.png" alt="MAiKL." onerror="this.outerHTML='<div class=\'logo-fallback\'>MAiKL.</div>'">`}
function footer(){const y=new Date().getFullYear();return `<footer class="footer"><div class="socials"><a class="social" href="${CFG.socials.telegram}" target="_blank" aria-label="Telegram"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.7 3.4 18.5 19c-.2 1.1-.9 1.4-1.8.9l-4.9-3.6-2.4 2.3c-.3.3-.5.5-1 .5l.4-5 9-8.1c.4-.4-.1-.6-.6-.2L6.1 12.8l-4.8-1.5c-1-.3-1.1-1 .2-1.5L20.2 2.6c.9-.3 1.7.2 1.5.8Z"/></svg></a><a class="social" href="${CFG.socials.vk}" target="_blank" aria-label="VK"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12.7 18.2C5.2 18.2.9 13.1.7 4.6h3.8c.1 6.2 2.9 8.9 5.1 9.5V4.6h3.6V10c2.2-.2 4.5-2.7 5.3-5.4h3.6c-.6 3.3-3.1 5.8-4.9 6.8 1.8.8 4.7 3 5.8 6.8h-4c-.9-2.6-3-4.6-5.8-4.9v4.9h-.5Z"/></svg></a><a class="social" href="${CFG.socials.instagram}" target="_blank" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 2h9.6A5.2 5.2 0 0 1 22 7.2v9.6a5.2 5.2 0 0 1-5.2 5.2H7.2A5.2 5.2 0 0 1 2 16.8V7.2A5.2 5.2 0 0 1 7.2 2Zm0 1.8a3.4 3.4 0 0 0-3.4 3.4v9.6a3.4 3.4 0 0 0 3.4 3.4h9.6a3.4 3.4 0 0 0 3.4-3.4V7.2a3.4 3.4 0 0 0-3.4-3.4H7.2Zm9.9 1.4a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4ZM12 6.9a5.1 5.1 0 1 1 0 10.2 5.1 5.1 0 0 1 0-10.2Zm0 1.8a3.3 3.3 0 1 0 0 6.6 3.3 3.3 0 0 0 0-6.6Z"/></svg></a></div><div>MAiKL. © 2019–${y}</div></footer>`}
function back(){return `<button class="back" data-back>← Назад</button>`}
function render(body,secondary=true){app.innerHTML=`${logo()}${body}${secondary?back():""}${footer()}`;app.querySelectorAll("[data-back]").forEach(x=>x.onclick=()=>history.back());app.querySelectorAll("[data-route]").forEach(x=>x.onclick=()=>go(x.dataset.route));window.scrollTo(0,0)}
function go(route,extra={}){history.pushState({route,extra},"",`#${route}`);Object.assign(state,extra,{route});view()}
window.addEventListener("popstate",e=>{state.route=e.state?.route||"home";Object.assign(state,e.state?.extra||{});view()});
function service(id){return SERVICES.find(x=>x.id===id)}
function homeCard(route,icon,title,sub){return `<button class="card home-row" data-route="${route}"><span class="home-picto"><img src="assets/home-icons/${icon}" alt=""></span><span><strong>${title}</strong><small>${sub}</small></span><span class="arrow">›</span></button>`}
function home(){render(`<section class="hero"><h1>Привет! Я MAiKL. Ассистент</h1><p>Помогу выбрать формат, найти время и записаться к MAiKL.</p></section><h2 class="section-title">Чем могу помочь?</h2><div class="grid">${homeCard("phone","phone.png","MAiKL. на связи","Аудиозвонок · сообщения + голосовые")}${homeCard("conversation","conversation.png","Разговорный с MAiKL.","Индивидуально или в группе")}${homeCard("lessons","courses.png","Уроки французского","B1 · B2 · C1 · C2 · DELF · DALF")}${homeCard("consult","consult.png","Консультация","15 · 30 · 60 минут")}${homeCard("services","services.png","Услуги","Студентам, компаниям, школам и переводчикам")}${homeCard("my","bookings.png","Мои записи","Ближайшие занятия и регулярные записи")}${homeCard("plus","plus.png","MAiKL.+","Telegram · VK Donut")}</div>${!API.configured()?`<p class="notice" style="margin-top:18px">Демо-режим: центральная база Yandex Cloud ещё не подключена. Записи сохраняются только на этом устройстве.</p>`:""}`,false)}
function officialIcon(name,cls="mini-picto maikl-sub-picto"){return `<span class="${cls}" aria-hidden="true"><img src="assets/official-icons/${name}.png" alt=""></span>`}
function miniIcon(id){const map={b1b2:"b1b2",c1c2:"c1c2",delfdalf:"delfdalf",conversation_individual:"conversation_individual",conversation_group:"conversation_group",consult15:"zoom",consult30:"zoom",consult60:"zoom",call15:"audio",call30:"audio",call60:"audio",messages15:"messages",messages30:"messages",messages60:"messages"};return officialIcon(map[id]||"zoom")}
function refIcon(name){return officialIcon(name)}
function categoryCard(route,icon,title,sub){return `<button class="card service-card" data-route="${route}">${refIcon(icon)}<span><strong>${title}</strong><em>${sub}</em></span><span class="arrow">›</span></button>`}
function consultMenu(){render(`<h1 class="page-title">Консультация</h1><div class="grid service-grid">${categoryCard("consultZoom","zoom","Zoom","Видеоконсультация · 15 / 30 / 60 минут")}${categoryCard("consultPhoneCall","audio","Аудиозвонок","FOCUS · SMALL-TALK · DISCUSSION")}${categoryCard("consultPhoneMessages","messages","Сообщения + голосовые","FOCUS · SMALL-TALK · DISCUSSION")}</div>`)}
function consultSmartphone(){render(`<h1 class="page-title">Консультация · Смартфон</h1><div class="grid service-grid">${categoryCard("consultPhoneCall","audio","Аудиозвонок","FOCUS · SMALL-TALK · DISCUSSION")}${categoryCard("consultPhoneMessages","messages","Сообщения + голосовые","FOCUS · SMALL-TALK · DISCUSSION")}</div>`)}
function phoneMenu(){render(`<h1 class="page-title">MAiKL. на связи</h1><div class="grid service-grid">${categoryCard("phoneCall","audio","Аудиозвонок","FOCUS · SMALL-TALK · DISCUSSION")}${categoryCard("phoneMessages","messages","Сообщения + голосовые","FOCUS · SMALL-TALK · DISCUSSION")}</div>`)}
function list(title,items){render(`<h1 class="page-title">${title}</h1><div class="grid service-grid">${items.map(x=>{const ri=x.id.startsWith("call")||x.id.startsWith("consult_phone")?refIcon("audio"):x.id.startsWith("messages")||x.id.startsWith("consult_msg")?refIcon("messages"):x.id.startsWith("consult_zoom")?refIcon("zoom"):miniIcon(x.id);return `<button class="card service-card direct-book-card" data-service="${x.id}">${ri}<span><strong>${esc(x.listTitle||x.title)}</strong><em>${esc(x.description||"")}</em><small><b>${rub(x.price)}</b> · ${x.duration} минут</small><span class="choose-time">Выбрать время →</span></span></button>`}).join("")}</div>`);app.querySelectorAll("[data-service]").forEach(b=>b.onclick=()=>go("calendar",{service:b.dataset.service,dayOffset:0,selectedDay:null,selected:null}))}
function dateRange(offset){const out=[];const now=new Date();for(let i=0;i<7;i++){const d=new Date(now.getTime()+(offset+i)*86400000);out.push(T.ymd(d,CFG.maiklTimezone))}return out}
async function calendar(){const s=service(state.service);render(`<h1 class="page-title">Свободное время</h1><div class="timezone-box">Время показано по вашему часовому поясу: <strong>${esc(state.zone)}</strong></div><div class="booking-rule">Запись доступна минимум за 2 часа до начала.</div><div class="legend"><span><i class="dot free-dot"></i> Свободно</span><span><i class="dot busy-dot"></i> Занято</span><span><i class="dot off-dot"></i> Нет приёма</span></div><div id="days" class="days-strip"></div><div id="times" class="times-panel"><div class="muted">Выберите день</div></div><div class="date-nav"><button class="link-btn" id="prevDates">← Раньше</button><button class="link-btn" id="nextDates">Другие даты →</button></div>`);document.getElementById("prevDates").onclick=()=>{state.dayOffset=Math.max(0,state.dayOffset-7);state.selectedDay=null;calendar()};document.getElementById("nextDates").onclick=()=>{state.dayOffset+=7;state.selectedDay=null;calendar()};await drawDays(s)}
async function drawDays(s){const dates=dateRange(state.dayOffset), baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone;let bookings=[];const start=T.toUtc(dates[0],"00:00",baseZone),end=new Date(T.toUtc(dates[6],"23:59",baseZone).getTime()+60000);if(API.configured()){try{bookings=await API.listBookings(start.toISOString(),end.toISOString())}catch(e){document.getElementById("times").innerHTML=`<div class="notice">Ошибка загрузки календаря: ${esc(e.message)}</div>`;return}}state.bookings=bookings;const days=document.getElementById("days");days.innerHTML=dates.map(d=>dayHtml(s,d)).join("");days.querySelectorAll(".day-choice:not(:disabled)").forEach(b=>b.onclick=()=>{state.selectedDay=b.dataset.date;drawDays(s)});if(!state.selectedDay){const first=days.querySelector(".day-choice.available");if(first)state.selectedDay=first.dataset.date}days.querySelectorAll(".day-choice").forEach(b=>b.classList.toggle("selected",b.dataset.date===state.selectedDay));drawTimes(s,state.selectedDay)}
function slotState(s,d,tm){const baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone,start=T.toUtc(d,tm,baseZone),iso=start.toISOString(),tooSoon=start.getTime()<Date.now()+(CFG.minimumBookingLeadMinutes||120)*60000;if(tooSoon)return {free:false,tooSoon:true,start};if(s.group){const count=state.bookings.filter(x=>x.service_id===s.id&&x.starts_at===iso&&x.status!=="cancelled").length;return {free:count<4,left:4-count,start}}const end=new Date(start.getTime()+s.duration*60000),busy=state.bookings.some(x=>x.status!=="cancelled"&&new Date(x.starts_at)<end&&new Date(x.ends_at)>start);return {free:!busy,start}}
function dayHtml(s,d){const baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone,noon=T.toUtc(d,"12:00",baseZone),slots=s.group?T.groupSlots(d):T.individualSlots(d,s.duration);let cls="off",label="Нет приёма";if(slots.length){const hasFree=slots.some(tm=>slotState(s,d,tm).free);cls=hasFree?"available":"full";label=hasFree?"Есть места":"Нет мест"}const wd=new Intl.DateTimeFormat("ru-RU",{timeZone:baseZone,weekday:"short"}).format(noon).replace(".","");const day=new Intl.DateTimeFormat("ru-RU",{timeZone:baseZone,day:"numeric",month:"short"}).format(noon).replace(".","");return `<button class="day-choice ${cls}" data-date="${d}" ${cls==="off"?"disabled":""}><span>${wd}</span><strong>${day}</strong><small>${label}</small></button>`}
function drawTimes(s,d){const root=document.getElementById("times");if(!d){root.innerHTML='<div class="muted">Нет доступных дней.</div>';return}const baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone,noon=T.toUtc(d,"12:00",baseZone),slots=s.group?T.groupSlots(d):T.individualSlots(d,s.duration);root.innerHTML=`<h3>${T.formatDate(noon,state.zone)}</h3><div class="slots">${slots.map(tm=>slotHtml(s,d,tm)).join("")}</div>`;root.querySelectorAll(".slot.free").forEach(b=>b.onclick=()=>{state.selected={date:b.dataset.date,time:b.dataset.time};go("booking")})}
function slotHtml(s,d,tm){const st=slotState(s,d,tm),local=T.formatTime(st.start,state.zone);if(st.tooSoon)return `<button class="slot unavailable" disabled>${local}<div class="capacity">Недоступно</div></button>`;if(s.group)return `<button class="slot ${st.free?"free":"busy"}" ${!st.free?"disabled":""} data-date="${d}" data-time="${tm}">${local}<div class="capacity">${st.free?`Осталось ${st.left} из 4`:"Мест нет"}</div></button>`;return `<button class="slot ${st.free?"free":"busy"}" ${!st.free?"disabled":""} data-date="${d}" data-time="${tm}">${local}<div class="capacity">${st.free?"Свободно":"Занято"}</div></button>`}
function booking(){const s=service(state.service),baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone,start=T.toUtc(state.selected.date,state.selected.time,baseZone);render(`<h1 class="page-title">Запись</h1><div class="summary"><strong>${esc(s.title)}</strong><br>${T.formatDate(start,state.zone)} · ${T.formatTime(start,state.zone)}<br>${s.duration} минут · ${rub(s.price)}</div>${!s.group?`<div class="field"><label>Как записаться?</label><div class="recurrence"><label><input type="radio" name="rec" value="once" checked> Один раз</label><label><input type="radio" name="rec" value="weekly"> Каждую неделю</label></div></div>`:""}<div class="field"><label>Уровень французского</label><select id="level"><option value="">Выберите уровень</option>${["B1","B2","C1","C2"].map(x=>`<option>${x}</option>`).join("")}<option>Другой / не знаю</option></select><a class="a12-help" href="${CFG.socials.telegram}" target="_blank"><strong>Уровень A1–A2?</strong> Я работаю с уровня B1, но могу порекомендовать проверенного преподавателя.</a></div><div class="field"><label>Комментарий</label><textarea id="note" placeholder="Необязательно"></textarea></div><button class="btn" id="confirm">Подтвердить запись</button><div id="msg"></div>`);document.getElementById("confirm").onclick=confirmBooking}
async function confirmBooking(){const s=service(state.service),level=document.getElementById("level").value,note=document.getElementById("note").value.trim(),msg=document.getElementById("msg");if(!level){msg.innerHTML='<p class="notice">Выберите уровень французского.</p>';return}const baseZone=s.group?CFG.groupTimezone:CFG.maiklTimezone,first=T.toUtc(state.selected.date,state.selected.time,baseZone);let starts=[first];const rec=document.querySelector('input[name="rec"]:checked')?.value;if(rec==="weekly"){const month=new Intl.DateTimeFormat("en",{timeZone:baseZone,month:"2-digit"}).format(first);for(let i=1;i<5;i++){const d=new Date(first.getTime()+i*7*86400000);if(new Intl.DateTimeFormat("en",{timeZone:baseZone,month:"2-digit"}).format(d)!==month)break;starts.push(d)}}const u=user();if(first.getTime()<Date.now()+(CFG.minimumBookingLeadMinutes||120)*60000){msg.innerHTML='<p class="notice">Этот слот уже нельзя забронировать: запись доступна минимум за 2 часа.</p>';return}try{document.getElementById("confirm").disabled=true;for(const st of starts){await API.createBooking({service_id:s.id,user_key:u.key,student_name:u.name,starts_at:st.toISOString(),ends_at:new Date(st.getTime()+s.duration*60000).toISOString(),level,comment:note,source:tg()?"telegram":"web",recurrence:rec||"once",group:Boolean(s.group)})}go("success",{count:starts.length})}catch(e){msg.innerHTML=`<p class="notice">Не удалось записаться: ${esc(e.message)}</p>`;document.getElementById("confirm").disabled=false}}
function success(){render(`<section class="success"><div class="check">✓</div><h1>Готово! Вы записаны к MAiKL.</h1><p class="lead">${state.count>1?`Создано записей: ${state.count}.`:"Запись сохранена."}</p><button class="btn" data-route="my">Мои записи</button></section>`)}
async function mine(){render(`<h1 class="page-title">Мои записи</h1><div id="mine" class="grid"><div class="muted">Загрузка…</div></div>`);const root=document.getElementById("mine");try{const rows=await API.myBookings(user().key);root.innerHTML=rows.length?rows.map(x=>{const s=service(x.service_id)||{title:x.service_id};const d=new Date(x.starts_at);return `<div class="detail"><strong>${esc(s.title)}</strong><p>${T.formatDate(d,state.zone)} · ${T.formatTime(d,state.zone)}</p><small class="muted">${esc(x.level||"")}</small></div>`}).join(""):'<div class="muted">У вас пока нет записей.</div>'}catch(e){root.innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
function services(){const items=[
  ["students","Для студентов","Помощь с французским под конкретную учебную задачу.","students.svg"],
  ["documents","Работа с документами","Документы и тексты на французском под вашу задачу.","documents.svg"],
  ["companies","Для компаний","Языковые решения для бизнеса и команд.","companies.svg"],
  ["schools","Для языковых школ","Сотрудничество и профессиональная поддержка школ.","schools.svg"],
  ["translators","Для переводчиков","Помощь с французским и языковыми задачами.","translators.svg"]
];render(`<h1 class="page-title">Услуги</h1><div class="grid service-grid">${items.map(([id,x,d,ic])=>`<button class="card service-card" data-product="${id}">${officialIcon(ic.replace(".svg",""))}<span><strong>${x}</strong><em>${d}</em><small><b>Стоимость — по запросу</b></small></span><span class="arrow">›</span></button>`).join("")}</div>`);app.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>go("serviceLinks",{product:b.dataset.product}))}
function serviceLinks(){const x=CFG.serviceLinks[state.product];if(!x)return services();render(`<h1 class="page-title">${esc(x.title)}</h1><p class="lead">Откройте описание услуги там, где вам удобнее.</p><div class="platform-links"><a class="platform-card" href="${x.telegram}" target="_blank">${officialIcon("telegram","platform-picto")}<span><strong>Telegram</strong><small>Открыть услугу напрямую</small></span><span class="arrow">›</span></a><a class="platform-card" href="${x.vk}" target="_blank">${officialIcon("vk","platform-picto")}<span><strong>VK</strong><small>Открыть товар напрямую</small></span><span class="arrow">›</span></a></div>`)}
function plus(){const tgReady=Boolean(CFG.maiklPlusTelegramUrl);render(`<h1 class="page-title">MAiKL.+</h1><p class="lead">Выберите удобный способ подписки.</p><div class="grid service-grid" style="margin-top:18px"><${tgReady?'a':'div'} class="card service-card plus-platform${tgReady?'':' disabled-card'}" ${tgReady?`href="${CFG.maiklPlusTelegramUrl}" target="_blank"`:''}>${officialIcon("telegram","platform-picto")}<span class="plus-copy"><strong>Telegram</strong><em>Подписка на MAiKL.+</em><small><b>250 ⭐ / 30 дней</b>${tgReady?'':' · ссылка будет подключена через MAiKL. Ассистент'}</small></span><span class="arrow">${tgReady?'›':'·'}</span></${tgReady?'a':'div'}><a class="card service-card plus-platform" href="${CFG.maiklPlusVkUrl}" target="_blank">${officialIcon("vk","platform-picto")}<span class="plus-copy"><strong>VK Donut</strong><em>Выберите подходящий вариант поддержки.</em><small><b>4 уровня подписки</b></small></span><span class="arrow">›</span></a></div>`)}
function view(){switch(state.route){case"home":return home();case"lessons":return list("Уроки французского",SERVICES.filter(x=>x.section==="lessons"));case"conversation":return list("Разговорный с MAiKL.",SERVICES.filter(x=>x.section==="conversation"));case"consult":return consultMenu();case"consultZoom":return list("Консультация · Zoom",SERVICES.filter(x=>x.section==="consult_zoom"));case"consultPhoneCall":return list("Консультация · Аудиозвонок",SERVICES.filter(x=>x.section==="consult_phone_call"));case"consultPhoneMessages":return list("Консультация · Сообщения + голосовые",SERVICES.filter(x=>x.section==="consult_phone_messages"));case"phone":return phoneMenu();case"phoneCall":return list("MAiKL. на связи · Аудиозвонок",SERVICES.filter(x=>x.section==="phone_call"));case"phoneMessages":return list("MAiKL. на связи · Сообщения + голосовые",SERVICES.filter(x=>x.section==="phone_messages"));case"calendar":return calendar();case"booking":return booking();case"my":return mine();case"services":return services();case"serviceLinks":return serviceLinks();case"plus":return plus();case"success":return success();default:return home()}}
let swipeStart=null;document.addEventListener("touchstart",e=>{if(e.touches.length!==1)return;const t=e.touches[0];if(t.clientX<=28)swipeStart={x:t.clientX,y:t.clientY,time:Date.now()};},{passive:true});document.addEventListener("touchend",e=>{if(!swipeStart||!e.changedTouches.length)return;const t=e.changedTouches[0],dx=t.clientX-swipeStart.x,dy=Math.abs(t.clientY-swipeStart.y),dt=Date.now()-swipeStart.time;swipeStart=null;if(state.route!=="home"&&dx>75&&dy<70&&dt<900)history.back();},{passive:true});
const q=new URLSearchParams(location.search),preset=q.get("service");if(preset&&service(preset)){state.service=preset;state.route="calendar"}history.replaceState({route:state.route},"",location.href);view();
})();
