const VK_BOOKING_URL="https://vk.ru/service-booking-177750329";
const TELEGRAM_CONTACT="maikl_prod";
const MAIKL_PLUS_URL="https://t.me/+OLayyhn3yRQ3MWFi";
const MAIKL_TIMEZONE="Europe/Moscow";

const LESSONS=[
["B1/B2","2 000 ₽","60 минут","Для общего прогресса, уверенности и системной практики."],
["C1/C2","3 000 ₽","60 минут","Продвинутый французский: точность, нюансы и естественная речь."],
["DELF/DALF","3 000 ₽","60 минут","Подготовка к экзамену с фокусом на нужный формат и результат."],
["ОГЭ/ЕГЭ","3 000 ₽","60 минут","Подготовка к экзамену: стратегия, практика и разбор слабых мест."]];
const CONSULT=[
["15 минут","750 ₽","Один конкретный вопрос или быстрый разбор."],
["30 минут","1 000 ₽","Разобрать вопрос подробнее и получить понятный план действий."],
["60 минут","2 000 ₽","Полноценная консультация по французскому или связанному запросу."]];

function tg(){return window.Telegram?.WebApp||null}
function initTelegram(){try{const a=tg();if(a){a.ready();a.expand();a.setHeaderColor?.("#f7f7f4");a.setBackgroundColor?.("#f7f7f4")}}catch(_){}}
function go(url){try{const a=tg();if(a?.openLink)return a.openLink(url)}catch(_){}window.location.href=url}
function openTelegramWithText(text){go(`https://t.me/${TELEGRAM_CONTACT}?text=${encodeURIComponent(text)}`)}
function toast(text){const el=document.createElement("div");el.className="toast";el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function esc(s=""){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function localTimezone(){return Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"}
function fmtInZone(date,zone){return new Intl.DateTimeFormat("ru-RU",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(date)}
function dateFromLocalInput(v){if(!v)return null;const d=new Date(v);return isNaN(d.getTime())?null:d}
function backButton(){return `<div class="topbar"><button class="back" data-back>← Назад</button><div class="top-mark">MAiKL.</div></div>`}
function render(html){document.getElementById("app").innerHTML=html;bindCommon();window.scrollTo({top:0,behavior:"instant"})}
function bindCommon(){document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>history.back());document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>navigate(b.dataset.route))}
function navigate(route,state={}){history.pushState({route,state},"",`#${route}`);routeView(route,state)}
function home(){render(document.getElementById("home-template").innerHTML)}
function routeView(route,state={}){if(route==="home")return home();if(route==="zoom")return zoom();if(route==="phone")return phone();if(route==="services")return services();if(route==="plus")return plus();if(route==="lesson-list")return lessonList();if(route==="conversation-list")return conversationList();if(route==="consultation-list")return consultationList();if(route==="bookable-detail")return bookableDetail(state);if(route==="request")return requestForm(state);if(route==="phone-maikl")return phoneMaikl();if(route==="phone-consult")return phoneConsult();if(route==="service-detail")return serviceDetail(state);home()}

function zoom(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">ВСТРЕТИТЬСЯ С MAiKL. В ZOOM</h1><p class="lead">Выбери формат встречи.</p><div class="cards" style="margin-top:20px"><button class="choice-card" data-route="lesson-list"><span class="icon">📚</span><span><strong>Уроки французского</strong><small>B1/B2 • C1/C2 • DELF/DALF • ОГЭ/ЕГЭ</small></span><span class="chev">›</span></button><button class="choice-card" data-route="conversation-list"><span class="icon">⭐</span><span><strong>Разговорный с MAiKL.</strong><small>Индивидуально или в группе</small></span><span class="chev">›</span></button><button class="choice-card" data-route="consultation-list"><span class="icon">🗣</span><span><strong>Консультация</strong><small>15 / 30 / 60 минут</small></span><span class="chev">›</span></button></div></section>`)}
function lessonList(){const rows=LESSONS.map((x,i)=>`<button class="choice-card" data-bookable="${i}"><span class="icon">📘</span><span><strong>${x[0]}</strong><small>${x[1]} • ${x[2]}</small></span><span class="chev">›</span></button>`).join("");render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">УРОКИ ФРАНЦУЗСКОГО</h1><p class="lead">Выбери направление.</p><div class="cards" style="margin-top:20px">${rows}</div></section>`);document.querySelectorAll("[data-bookable]").forEach(el=>el.onclick=()=>{const x=LESSONS[+el.dataset.bookable];navigate("bookable-detail",{title:x[0],price:x[1],duration:x[2],desc:x[3]})})}
function conversationList(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">РАЗГОВОРНЫЙ С MAiKL.</h1><p class="lead">Выбери формат.</p><div class="cards" style="margin-top:20px"><button class="choice-card" id="conv-ind"><span class="icon">👤</span><span><strong>Индивидуально</strong><small>2 000 ₽ • 60 минут</small></span><span class="chev">›</span></button><button class="choice-card" id="conv-group"><span class="icon">👥</span><span><strong>В группе</strong><small>1 500 ₽ / человек • 90 минут</small></span><span class="chev">›</span></button></div></section>`);document.getElementById("conv-ind").onclick=()=>navigate("bookable-detail",{title:"Разговорный с MAiKL. — индивидуально",price:"2 000 ₽",duration:"60 минут",desc:"Разговор один на один: естественно, без учебников и заготовленных тем."});document.getElementById("conv-group").onclick=()=>navigate("request",{title:"Разговорный с MAiKL. — в группе",price:"1 500 ₽ / человек",duration:"90 минут",requestType:"Хочу в группу",cta:"ХОЧУ В ГРУППУ",extra:"Укажи свой уровень французского и удобное время."})}
function consultationList(){const rows=CONSULT.map((x,i)=>`<button class="choice-card" data-cons="${i}"><span class="icon">🗣</span><span><strong>${x[0]}</strong><small>${x[1]}</small></span><span class="chev">›</span></button>`).join("");render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">КОНСУЛЬТАЦИЯ</h1><p class="lead">Выбери длительность.</p><div class="cards" style="margin-top:20px">${rows}</div></section>`);document.querySelectorAll("[data-cons]").forEach(el=>el.onclick=()=>{const x=CONSULT[+el.dataset.cons];navigate("bookable-detail",{title:`Консультация • ${x[0]}`,price:x[1],duration:x[0],desc:x[2]})})}
function bookableDetail(s){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 3</div><div class="detail"><h3>${esc(s.title||"Услуга")}</h3><p>${esc(s.desc||"")}</p><div class="price">${esc(s.price||"")}</div><div class="meta">${esc(s.duration||"")}</div><button class="cta" id="vk-book">ЗАПИСАТЬСЯ</button><p class="helper">Кнопка сразу открывает VK «Моё время». Календарь не дублируется внутри Mini App.</p></div></section>`);document.getElementById("vk-book").onclick=()=>go(VK_BOOKING_URL)}

function phone(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">MAiKL. В ТВОЁМ СМАРТФОНЕ</h1><p class="lead">Практика и помощь прямо в Telegram.</p><div class="cards" style="margin-top:20px"><button class="choice-card" data-route="phone-maikl"><span class="icon">📱</span><span><strong>MAiKL. на связи</strong><small>Звонки или сообщения + голосовые</small></span><span class="chev">›</span></button><button class="choice-card" data-route="phone-consult"><span class="icon">🗣</span><span><strong>Консультация</strong><small>Конкретный вопрос / помощь / совет</small></span><span class="chev">›</span></button></div></section>`)}
function phoneMaikl(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">MAiKL. НА СВЯЗИ</h1><p class="lead">Выбери формат и длительность.</p><div class="detail" style="margin-top:20px"><h3>Аудиозвонок</h3><div class="option-list"><button class="option req" data-format="Аудиозвонок" data-dur="15 минут" data-price="750 ₽"><b>15 минут</b><span>750 ₽ ›</span></button><button class="option req" data-format="Аудиозвонок" data-dur="30 минут" data-price="1 000 ₽"><b>30 минут</b><span>1 000 ₽ ›</span></button><button class="option req" data-format="Аудиозвонок" data-dur="60 минут" data-price="1 500 ₽"><b>60 минут</b><span>1 500 ₽ ›</span></button></div><div class="hr"></div><h3>Сообщения + голосовые</h3><div class="option-list"><button class="option req" data-format="Сообщения + голосовые" data-dur="15 минут" data-price="500 ₽"><b>15 минут</b><span>500 ₽ ›</span></button><button class="option req" data-format="Сообщения + голосовые" data-dur="30 минут" data-price="750 ₽"><b>30 минут</b><span>750 ₽ ›</span></button><button class="option req" data-format="Сообщения + голосовые" data-dur="60 минут" data-price="1 000 ₽"><b>60 минут</b><span>1 000 ₽ ›</span></button></div></div></section>`);document.querySelectorAll(".req").forEach(el=>el.onclick=()=>navigate("request",{title:`MAiKL. на связи • ${el.dataset.format}`,price:el.dataset.price,duration:el.dataset.dur,requestType:"MAiKL. на связи",cta:"НАПИСАТЬ MAiKL.",extra:"Выбери желаемую дату и время — это заявка, а не подтверждённая запись."}))}
function phoneConsult(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">КОНСУЛЬТАЦИЯ В TELEGRAM</h1><p class="lead">Выбери длительность — дальше укажешь желаемое время и вопрос.</p><div class="cards" style="margin-top:20px"><button class="choice-card phc" data-dur="15 минут" data-price="750 ₽"><span class="icon">🗣</span><span><strong>15 минут</strong><small>750 ₽</small></span><span class="chev">›</span></button><button class="choice-card phc" data-dur="30 минут" data-price="1 000 ₽"><span class="icon">🗣</span><span><strong>30 минут</strong><small>1 000 ₽</small></span><span class="chev">›</span></button><button class="choice-card phc" data-dur="60 минут" data-price="2 000 ₽"><span class="icon">🗣</span><span><strong>60 минут</strong><small>2 000 ₽</small></span><span class="chev">›</span></button></div></section>`);document.querySelectorAll(".phc").forEach(el=>el.onclick=()=>navigate("request",{title:"Консультация в Telegram",duration:el.dataset.dur,price:el.dataset.price,requestType:"Консультация",cta:"НАПИСАТЬ MAiKL.",extra:"Коротко напиши вопрос и выбери желаемую дату/время."}))}

const serviceTypes=[["Услуги для студентов","🎓"],["Составление документов","📄"],["Услуги для компаний","🏢"],["Услуги для языковых школ","🏫"],["Услуги для переводчиков","🌍"]];
function services(){const rows=serviceTypes.map((x,i)=>`<button class="choice-card" data-srv="${i}"><span class="icon">${x[1]}</span><span><strong>${x[0]}</strong><small>Стоимость — по запросу</small></span><span class="chev">›</span></button>`).join("");render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 2</div><h1 class="page-title">УСЛУГИ</h1><p class="lead">Выбери направление.</p><div class="cards" style="margin-top:20px">${rows}</div></section>`);document.querySelectorAll("[data-srv]").forEach(el=>el.onclick=()=>{const x=serviceTypes[+el.dataset.srv];navigate("service-detail",{title:x[0],icon:x[1]})})}
function serviceDetail(s){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 3</div><div class="detail"><span class="badge">${esc(s.icon||"🎟")} УСЛУГА</span><h3 style="margin-top:14px">${esc(s.title||"Услуга")}</h3><p>Опиши задачу, желаемый срок и удобное время для связи. MAiKL. получит уже структурированную заявку.</p><div class="price">По запросу</div><button class="cta secondary" id="service-request">НАПИСАТЬ MAiKL.</button></div></section>`);document.getElementById("service-request").onclick=()=>navigate("request",{title:s.title,price:"По запросу",requestType:s.title,cta:"НАПИСАТЬ MAiKL.",extra:"Опиши задачу и желаемый срок."})}

function requestForm(s){const tz=localTimezone();render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 3 • ЗАЯВКА</div><div class="detail"><h3>${esc(s.title||"Заявка")}</h3>${s.price?`<div class="price">${esc(s.price)}</div>`:""}${s.duration?`<div class="meta">${esc(s.duration)}</div>`:""}<p>${esc(s.extra||"")}</p><div class="tz-box"><strong>🕒 Время покажем в твоём часовом поясе</strong>Сейчас определён: <span id="tz-name">${esc(tz)}</span><br>MAiKL. увидит также эквивалент по московскому времени.</div><div class="form"><div class="field"><label for="when">Желаемая дата и время</label><input id="when" type="datetime-local" /></div><div class="field"><label for="level">Уровень французского / короткая пометка</label><input id="level" type="text" placeholder="Например: B1" /></div><div class="field"><label for="note">Что важно знать MAiKL.?</label><textarea id="note" placeholder="Вопрос, задача, пожелания..."></textarea></div><div id="time-preview" class="tz-box" style="display:none"></div><button class="cta secondary" id="send-request">${esc(s.cta||"НАПИСАТЬ MAiKL.")}</button><p class="helper">Это заявка на желаемое время, а не автоматическое подтверждение брони.</p></div></div></section>`);const when=document.getElementById("when"),preview=document.getElementById("time-preview");function updatePreview(){const d=dateFromLocalInput(when.value);if(!d){preview.style.display="none";return}preview.style.display="block";preview.innerHTML=`<strong>Твоё устройство:</strong> ${esc(fmtInZone(d,tz))} (${esc(tz)})<br><strong>Для MAiKL.:</strong> ${esc(fmtInZone(d,MAIKL_TIMEZONE))} (${MAIKL_TIMEZONE})`}when.oninput=updatePreview;when.onchange=updatePreview;document.getElementById("send-request").onclick=async()=>{const d=dateFromLocalInput(when.value),level=document.getElementById("level").value.trim(),note=document.getElementById("note").value.trim();const lines=["Привет, MAiKL.! 👋",`Заявка: ${s.requestType||s.title||"услуга"}`,s.duration?`Формат / длительность: ${s.duration}`:null,s.price?`Стоимость: ${s.price}`:null,d?`Желаемое время клиента: ${fmtInZone(d,tz)} (${tz})`:"Желаемое время: не указано",d?`Эквивалент для MAiKL.: ${fmtInZone(d,MAIKL_TIMEZONE)} (${MAIKL_TIMEZONE})`:null,level?`Уровень / пометка: ${level}`:null,note?`Комментарий: ${note}`:null].filter(Boolean);const text=lines.join("\n");try{await navigator.clipboard.writeText(text);toast("Заявка скопирована ✓")}catch(_){}openTelegramWithText(text)}}

function plus(){render(`<section class="screen">${backButton()}<div class="kicker">УРОВЕНЬ 3</div><div class="detail"><span class="badge">💎 TELEGRAM</span><h3 style="margin-top:14px">MAiKL.+</h3><p>Закрытый контент, закрытый чат подписчиков, где есть сам MAiKL., и поддержка развития проекта.</p><div class="price">250 ⭐ / месяц</div><button class="cta" id="plus-go">ПОДПИСАТЬСЯ</button></div></section>`);document.getElementById("plus-go").onclick=()=>go(MAIKL_PLUS_URL)}

window.addEventListener("popstate",()=>{const route=(location.hash||"#home").slice(1);routeView(route,history.state?.state||{})});
document.addEventListener("DOMContentLoaded",()=>{initTelegram();const route=(location.hash||"#home").slice(1);if(route==="home")home();else routeView(route,{})});
